version: "3.9"
services:
  app:
    container_name: labscontrolapp
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-application
    volumes:
      - war:/home/target
  mysql:
    container_name: mysql_57
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=labscontrol
    ports:
      - "3306:3306"
  payara-server:
    container_name: payara_server
    build:
      context: dockerfiles
      dockerfile: Dockerfile-payara-server
    ports:
      - "4848:4848"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - war:/opt/deployment
    depends_on:
      - mysql
      - app
volumes:
  war:
    external: false