version: "3.9"
services:
  mysql:
    container_name: mysql_57
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=labscontrol
    ports:
      - "3306:3306"
  app:
    container_name: labscontrolapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4848:4848"
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mysql