FROM maven:3.6.3-jdk-8-slim

COPY src /home/app/src
COPY pom.xml /home/app

RUN mvn -f /home/app/pom.xml clean package

RUN mkdir /home/target \
    && mv /home/app/target/labscontrol.war /home/target/labscontrol.war

VOLUME /home/target

